//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ArticleId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Tags { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ValueStreamId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> LikeCount { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CommentLinkId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual ValueStream ValueStream { get; set; }
    }
}
